openapi: 3.0.0
info:
  title: Yandex Search API
  version: 1.2.0
  description: API для выполнения поиска на платформе Яндекс, включая текстовый, голосовой поиск, загрузку файлов, а также поиск по фото.
servers:
  - url: https://api.yandex.ru/search/v1
    description: Основной сервер API

paths:
  /search:
    get:
      summary: Текстовый поиск
      description: Выполняет поиск по ключевым словам и возвращает текстовые результаты.
      parameters:
        - name: query
          in: query
          required: true
          description: Ключевые слова для поиска.
          schema:
            type: string
        - name: language
          in: query
          description: Язык результатов поиска (например, ru, en).
          schema:
            type: string
            default: ru
        - name: region
          in: query
          description: Регион пользователя (например, Москва, Санкт-Петербург).
          schema:
            type: string
        - name: page
          in: query
          description: Номер страницы для пагинации.
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: Количество результатов на странице.
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        link:
                          type: string
                        snippet:
                          type: string
                  totalResults:
                    type: integer
                  currentPage:
                    type: integer
        '400':
          description: Неверный запрос
        '500':
          description: Внутренняя ошибка сервера

  /search-by-photo:
    post:
      summary: Поиск по фотографии
      description: Загружает фотографию и возвращает результаты, связанные с изображением.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Загружаемая фотография.
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        link:
                          type: string
                        thumbnail:
                          type: string
        '400':
          description: Неверный запрос
        '500':
          description: Внутренняя ошибка сервера

  /search-by-file:
    post:
      summary: Поиск по файлу
      description: Загружает файл для анализа и выполняет поиск, основанный на содержимом файла.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Загружаемый файл (например, текстовый документ или PDF).
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        link:
                          type: string
        '400':
          description: Неверный запрос
        '500':
          description: Внутренняя ошибка сервера

  /voice-search:
    post:
      summary: Голосовой поиск
      description: Загружает аудиофайл с голосовым запросом и выполняет поиск.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                audio:
                  type: string
                  format: binary
                  description: Загружаемый аудиофайл с голосовым запросом.
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        link:
                          type: string
        '400':
          description: Неверный запрос
        '500':
          description: Внутренняя ошибка сервера
